--Day 5

--ASSIGNMENT
--(1)
SELECT E.JOINING_DATE AS 'Joining Date', I.INCENTIVE_DATE AS 'Incentive Date',DATEDIFF(day,E.JOINING_DATE,I.INCENTIVE_DATE) AS 'Difference of Date'
FROM Employee1 E JOIN Incentives I ON EMPLOYEE_ID = EMPLOYEE_REF_ID

--(2)
SELECT E.FIRST_NAME AS 'First Name',I.INCENTIVE_AMOUNT AS 'Incentive Amount'
FROM Employee1 E JOIN Incentives I ON EMPLOYEE_ID = EMPLOYEE_REF_ID
WHERE I.INCENTIVE_AMOUNT > 3000

--(3)
SELECT E.FIRST_NAME AS 'First Name',I.INCENTIVE_AMOUNT AS 'Incentive Amount'
FROM Employee1 E LEFT JOIN Incentives I ON EMPLOYEE_ID = EMPLOYEE_REF_ID

--(4)
SELECT LE.FIRST_NAME +' ' +LE.LAST_NAME AS 'Employee Name',RE.FIRST_NAME + ' ' + RE.LAST_NAME AS 'Manager Name'
FROM Employee1 LE left JOIN Employee1 RE ON LE.MANAGER_ID = RE.EMPLOYEE_ID

--(5)
SELECT E.FIRST_NAME AS 'First Name' ,ISNULL(I.INCENTIVE_AMOUNT,0) AS 'Incentive Amount' 
FROM Employee1 E LEFT JOIN Incentives I ON E.EMPLOYEE_ID = I.EMPLOYEE_REF_ID